name: git-collab

on:
  push:
    branches:
      - master  

permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --index-url=https://dl.cloudsmith.io/Kj9ZYSSp2IpguP7w/orgcs/gharepo/python/simple/

      - name: Create a Python package
        run: |
          cd nyapkg
          pip3 install setuptools
          python setup.py sdist bdist_wheel
          cd ..

      - name: List package files
        run: ls -l nyapkg/dist/

      - name: Upload Package Artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: nyapkg/dist/*.tar.gz
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get OIDC token
        id: get_token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          echo $value
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"nyiservice-BjQf\"}" https://api.cloudsmith.io/openid/orgcs/ | jq -r '.token')
          echo $token
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'
          
          # Save token to a file
          echo "$token" > cloudsmith_api_key.txt

      - name: Upload API Key Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cloudsmith-credentials
          path: cloudsmith_api_key.txt
          retention-days: 1 
          if-no-files-found: error 
          visibility: private

      - name: Cloudsmith CLI Setup
        env:
          CLOUDSMITH_API_KEY: ${{ steps.get_token.outputs.token }}
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with: 
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          oidc-namespace: 'orgcs'
          oidc-service-slug: 'nyiservice-BjQf'

      - name: Checking the user details
        env:
          CLOUDSMITH_API_KEY: ${{ steps.get_token.outputs.token }}
        run: |
          echo "Cloudsmith API Key acquired successfully"
          cloudsmith whoami

  push:
    runs-on: ubuntu-latest
    needs: deploy
    name: Python Push Demo
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Download API Key Artifact
        uses: actions/download-artifact@v4
        with:
          name: cloudsmith-credentials
          path: ./credentials

      - name: Set API Key
        run: |
          CLOUDSMITH_API_KEY=$(cat ./credentials/cloudsmith_api_key.txt)
          echo "CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY" >> $GITHUB_ENV
          rm -f ./credentials/cloudsmith_api_key.txt

      - name: Download Package Artifact
        uses: actions/download-artifact@v4
        with:
          name: python-package
          path: dist

      - name: Push Static Package
        id: push-1
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "orgcs"
          repo: "gharepo"
          republish: "true"
          file: "./nyapkg-3.0.1.tar.gz"

      - name: Push Built Package
        id: push-2
        uses: cloudsmith-io/action@v0.5.3
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "orgcs"
          repo: "gharepo"
          file: "dist/*.tar.gz"