name: git-collab

on:
  push:
    branches:
      - master  

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt --index-url=https://dl.cloudsmith.io/Kj9ZYSSp2IpguP7w/orgcs/gharepo/python/simple/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    outputs:
      cloudsmith_api_key: ${{ steps.get_token.outputs.cloudsmith_api_key }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Get OIDC token
        id: get_token
        run: |
          value=$(curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq '.value')
          echo $value
          token=$(curl -X POST -H "Content-Type: application/json" -d "{\"oidc_token\":$value, \"service_slug\":\"nyiservice-BjQf\"}" https://api.cloudsmith.io/openid/orgcs/ | jq -r '.token')
          echo $token
          curl --request GET --url https://api.cloudsmith.io/v1/user/self/ --header "X-Api-Key:Bearer $token" --header 'accept: application/json'

          echo "::set-output name=cloudsmith_api_key::$token"
          echo "CLOUDSMITH_API_KEY=$token" >> $GITHUB_ENV

      - name: Cloudsmith CLI Setup
        uses: cloudsmith-io/cloudsmith-cli-action@v1.0.0
        with: 
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          oidc-namespace: 'orgcs'
          oidc-service-slug: 'nyiservice-BjQf'

      - name: Checking the user details
        run: |
          echo "Cloudsmith API Key: ${{ steps.get_token.outputs.cloudsmith_api_key }}"
          cloudsmith whoami

  push:
    runs-on: ubuntu-latest
    needs: deploy
    name: Python Push Demo
    steps:
      - name: Use Cloudsmith API Key
        run: echo "CLOUDSMITH_API_KEY=${{ needs.deploy.outputs.cloudsmith_api_key }}" >> $GITHUB_ENV  

      - name: Check out code
        uses: actions/checkout@v2

      - name: Push to Cloudsmith
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ env.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "python"
          owner: "orgcs"
          repo: "gharepo"
          republish: "true"
          file: "./nyapkg-3.2.2-beta.8.tgz"
